- src/kernel/triton_code_gen.cc
This PR fixes the following assertion failure in Triton codegen: https://github.com/mirage-project/mirage/blob/4549f27d13475852f433448d2df24a239f72947f/src/kernel/triton_code_gen.cc#L349
> [Triton CodeGen] Fix an issue when generating Triton programs from mugraphs

- include/mirage/cpu/cmem_tensor.h
- include/mirage/kernel/device_tensor.h
- include/mirage/threadblock/smem_tensor.h
- src/kernel/cuda/customized_kernel.cu
Previously we use `#define` to define `MAX_TENSOR_DIMS` in `cmem_tensor.h`, `device_tensor.h`, and `smem_tensor.h`. This may cause unexpected behaviour when we include two or more these files, since `#define` is not controlled by namespace. This may cause potential bug when `MAX_TENSOR_DIMS` are not the same among those files.
In this commit I use `constexpr` to define `MAX_TENSOR_DIMS`, which won't cause this problem.
> [fix] Use `constexpr` instead of `define` to define MAX_TENSOR_DIMS

- cpp_examples/group_query_attn_spec_decode.cc
- include/mirage/kernel/customized.h
- include/mirage/kernel/graph.h
- src/kernel/customized.cc
- src/kernel/graph.cc
This PR aims to remove all usage of ExecutionPlan in Mirage. ExecutionPlan are functionally equivalent to threadblock::Graph.
> [Deprecate ExecutionPlan] Initial attempt to make ExecutionPlan deprecated

- INSTALL.md
- MANIFEST.in
- python/mirage/kernel.py
- requirements.txt
- setup.py
If env `MIRAGE_ROOT` is not set, it will search header files in the mirage package directory, where all necessary runtime headers are already included. 
Test:
Install mirage in a new python environment, and run `demo/demo_jit.py`. May also need torch.
> Include header files for JIT compilation. MIRAGE_ROOT is no longer required.

- python/mirage/kernel.py
Searched valid mugraphs is transpiled one by one, which is too slow. 
Cost Time comparision([demo_gated_mlp.py](https://github.com/mirage-project/mirage/blob/main/demo/demo_gated_mlp.py)): 
1m34s VS 13m36s
resolved #118
> [Transpiler] Parallel transpile to accelerate superoptimize speed 10x faster

- src/transpiler/resolve_tensor_layout.cc
Add shared memory usage as part of the cost when determining the layouts for stensors
Linked Issues:
- Issue #
- Closes #114
> [Transpiler] Add shared memory usage as part of the cost when determining the layouts for stensors

- include/mirage/search/verification/output_match.h
- include/mirage/transpiler/error_types.h
- include/mirage/transpiler/structs.h
- src/transpiler/resolve_tensor_layout.cc
- src/transpiler/sched_tb_graph.cc
- src/transpiler/transpiler_kn.cc
- src/transpiler/transpiler_tb.cc
This change introduces a `state` field in `TranspileResult`, which allows the transpiler to label some mugraphs as invalid when generating CUDA code.
Linked Issues:
- Issue #
- Closes #
> [Transpiler] Allow the transpiler to return errors for untranspilable muGraphs

- scripts/partition_graph.py
Implements the conversion of subgraphs generated by the partition_graph function into valid Mirage kernel graphs. This allows them to be compiled and their performance tested.
> Subgraph to Kernel Graph Conversion and Timing

- include/mirage/nki_transpiler/transpile.h
- src/nki_transpiler/transpile.cc
- src/nki_transpiler/transpile_tb.cc
When both inputs parallel axis is mapped to physical partition dimension, it is possible to have their contraction axis sizes greater than 128, this requires us to do a transpose before performing matmul, In NKI transpose operation the partition dimension of resulting tile after transpose should be <= 128, hence we should split along the contraction dimension before doing transpose.
This is a special case, only happens when both inputs parallel axis is mapped to partition dimension, all other cases shall be correct.
Possible next step is making the accumulation stensors as psum tiles explicitly.
@jiazhihao It would be helpful if you could take a look at this commit for correctness issues if any. thanks
Linked Issues:
- Issue #
Issues closed …
>  Split matmul along contraction axis on transpose

- python/mirage/kernel.py
- setup.py
1. copy `mirage/transpiler/runtime/*` to `python/mirage/include/mirage/transpiler/runtime/*` instead of `python/mirage/include/include/mirage/transpiler/runtime/*`.
2. Because `pip install -e . `and `pip install .` have different directory structure, we need to check the directory structure to find the correct important paths.
3. Copy `python/mirage/include/mirage/config.h` which is included by `python/mirage/include/mirage/transpiler/runtime/threadblock/utils.h`.
Linked Issues:
- Issue #209 
- Closes #
> Support both editable and normal install path

- src/transpiler/transpiler_tb.cc
A bug caused by the previous deepseek_fix, should keep the Matmul aligned input shape consistent with input shape, both 2-dim.
Linked Issues:
- Issue #
- Closes #
> Bug Fix: Matmul Input aligned dimension

- demo/triton_rms_norm.py
- include/mirage/triton_transpiler/runtime/triton_kernels.py
- python/mirage/kernel.py
- setup.py
1. Move Triton runtime under triton_transpiler/ instead of transpiler/ as once talked about
2. Update triton example to current version
Linked Issues:
- Issue #
- Closes #
> [Triton] Move Triton runtime under triton_transpiler/ instead of transpiler/

- scripts/op.py
- scripts/partition_graph.py
This pull request adds support for the operators needed for Qwen to be properly partitioned, as well as some missing operators that were not previously supported.
- Adds support for Sigmoid, Softmax, Neg, Rec, Square, RMSNorm, and ReduceSum operators
- Sigmoid, Softmax, Neg, and Rec all require constants, so support is added for constant-value matrices to the conversion to kernel graph and timing code
- Added support for additional arguments (i.e. axis) and kwargs to operator class to support above additions
> Added support for all Qwen operators

- include/mirage/search/search_c.h
- python/mirage/_cython/CCore.pxd
- python/mirage/_cython/core.pyx
- python/mirage/kernel.py
- src/search/search_c.cc
This PR exposes the json functionalities in the C++ search side so that user's can call to_json and from_json to convert KNGraph objects into a json file.
Linked Issues:
- Issue #
- Closes #
> Exposed json functionalities to Python interface

- include/mirage/persistent_kernel/tasks/linear.cuh
- include/mirage/persistent_kernel/tasks/norm_linear.cuh
- include/mirage/persistent_kernel/tasks/reduction.cuh
- include/mirage/persistent_kernel/tasks/silu_mul_linear.cuh
During the computation of `MatMul` in a threadblock, we split `N` dimension across `NUM_WARP_N` warps and `K` dimension across `NUM_WARP_K` warps, where `NUM_WARP_N = min(OUTPUT_SIZE / 16, 4)`  and `NUM_WARP_K = 4 / NUM_WARP_N`
> implement adaptive thread layout of MMA

- include/mirage/persistent_kernel/persistent_kernel.cuh
- include/mirage/persistent_kernel/tasks/argmax.cuh
Current argmax only use one block's capability. Aim to change it to 2 step argmax leveraging multiple blocks.
This involves both runtime and task generation change. This PR only includes the runtime part.
For `argmax_partial` task:
* input: a matrix of `bfloat16` with shape [1, vocab_size // num_tasks]
* output1: a matrix of `bfloat16` with shape [1, 1]
* output2: a matrix of `int64_t` with shape [1,1]
* partial_vocab_size
* index_offset
For `argmax_reduction` task:
* input1: a matrix of `bfloat16` with shape [1, num_tasks]
* input2: a matrix of `int64_t` with shape [1, num_tasks]
* output: a matrix of `int64_t` with shape [1,1]
* num_partial_tasks
Linked Issues:
- Issue #281 
- Closes #
> Argmax Modification

- demo/qwen3/models/modeling_qwen3.py
- include/mirage/persistent_kernel/tasks/linear.cuh
- include/mirage/persistent_kernel/tasks/silu_mul_linear.cuh
- tests/runtime_python/runtime_kernel_wrapper.cu
- Compute the offsets of STensors in compiling stage
- Increase `TILE_SIZE` to 128
- Support more `OUTPUT_SIZE`
- Fuse `silu` and `mul`
Linked Issues:
- Issue #305
> optimize `linear` and `silu_mul_linear` tasks

- include/mirage/persistent_kernel/tasks/norm_linear.cuh
- Compute the offsets of STensors in compiling stage
- Increase `TILE_SIZE` to 128
- TODO: adjust `OUTPUT_SIZE` to multiple of 128
Linked Issues:
- Issue #305
> optimize `norm_linear` task

- demo/qwen3/models/modeling_qwen3.py
Replace flashinfer dependency with pytorch api.
Results align with previous outputs. After iterations, accumulation of precision difference will make later tokens different.
Linked Issues:
- Issue #320 
- Closes #
> Remove flashinfer dependency

- include/mirage/persistent_kernel/tasks/linear.cuh
- include/mirage/persistent_kernel/tasks/matmul_demo.cuh
- include/mirage/persistent_kernel/tasks/norm_linear.cuh
- include/mirage/persistent_kernel/tasks/silu_mul_linear.cuh
- include/mirage/persistent_kernel/tasks/single_batch_decoding.cuh
- include/mirage/persistent_kernel/tasks/single_batch_gqa.cuh
- include/mirage/persistent_kernel/tasks/utils.cuh
- tests/runtime_python/runtime_kernel_wrapper.cu
- tests/runtime_python/test_alignment_norm_linear.py
1. Clear buffers in a unified way
2. Fix outdated test wrapper
Alignment ratio tests all close to 1.0. Example:
```
=== Testing output_size = 64 ===
Ratio (kernel / torch):
tensor([[1.0078, 1.0000, 1.0000, 1.0000, 0.9922, 1.0156, 1.0156, 1.0078, 1.0078,
1.0000, 1.0078, 1.0078, 1.0156, 1.0000, 0.9766, 1.0000, 1.0000, 0.9922,
1.0000, 1.0000, 1.0000, 1.0078, 1.0078, 0.8984, 1.0078, 1.0156, 1.0000,
1.0078, 0.9961, 0.9844, 1.0000, 1.0078, 1.1562, 1.0078, 1.0078, 0.9961,
1.0000, 0.9883, 1.0078, 0.9883, 1.0156, 1.0000, 1.0078, 0.9922, 1.0156,
1.0078, 1.0078, 1.0156, 1.0000, 0.9961, 1.0000, 0.9805, 1.0078, 1.0000,
1.0078, 1.0000, 1.0000, 1.0000, 1.0000, 0.9922, 1.0000, 1.1719, 1.0000,
1.0078]], device='cuda:0', dtype=torch.bfloat16)
Average time over 1000 runs: …
```
> Clear buffers in a unified way

- python/mirage/persistent_kernel.py
The compiler used to generate tmp files directly in `/tmp`, however, in the case where a cluster is shared by multiple users, that would lead to permission issue -- one cannot overwrite other's file. We should generate a personal tmp dir in `/tmp` to avoid that.
> fix tmp file permission issue

- demo/qwen3/demo.py
- include/mirage/persistent_kernel/persistent_kernel.cuh
- include/mirage/persistent_kernel/tasks/embedding.cuh
- python/mirage/persistent_kernel.py
- src/kernel/task_register.cc
There are some hardcode for **Qwen3-8B** and **A100**, this PR supports more models and GPUs, but there're something still in draft stage, like to how define `num_workers`, `num_local_schedulers` and `num_remote_schedulers` automatically, any insights would be very appreciated! 
Linked Issues:
- Issue #336
> Fix some hardcode

- include/mirage/persistent_kernel/tasks/norm.cuh
- tests/runtime_python/runtime_kernel_wrapper.cu
- tests/runtime_python/test_window_rmsnorm.py
This PR introduces a window rmsnorm kernel, which will be used in window attention kernel for speculative decoding.
Linked Issues:
- Issue #329
- Closes #
> Introduce window rmsnorm kernel

- README.md
Previously, the guidance to set the environment variable is `echo MIRAGE_HOME=$pwd`. However there is no variable called `pwd`, we need to execute the `pwd` instruction to get the path. 
I change it to `echo MIRAGE_HOME=$(pwd)`
Linked Issues:
- Issue #
- Closes #
> Fix bug in setting `MIRAGE_HOME` in README

- include/mirage/persistent_kernel/runtime_header.h
This is a bugfix for certain GPUs not generating any output tokens. The default MAX_SHARE_MEMORY_SIZE was `150 kb` but this was larger than the max supported shared memory per block for some GPUs. Here we set it based off compute capability. These numbers were found by via a simple cuda program:
```cpp
#include <cuda_runtime.h>
#include <iostream>
auto main() -> int {
int device;
cudaDeviceProp prop;
cudaGetDevice(&device);
cudaGetDeviceProperties(&prop, device);
std::cout << "Device: " << prop.name << std::endl;
std::cout << "Compute Capability: " << prop.major << "." << prop.minor << std::endl;
std::cout << "Shared Memory per Block: " << prop.sharedMemPerBlock << " bytes" << std::endl;
std::cout << "Shared Memory per Multiprocessor: " << …
```
> set MAX_SHARE_MEMORY_SIZE based off compute capability

- include/mirage/persistent_kernel/runtime_header.h
- include/mirage/persistent_kernel/tasks/norm_linear.cuh
1. fix MAX_OUTPUT_ATOM_SIZE calculation
2.Change else branch of smem to 160*1024 for dev on A100
BS=1:
rms_norm_1: 60us
linear: 30us
rms_norm-2: 157us
silu_mul_linear: 91us （已编辑） 
BS=8:
rmsnorm_linear_1: 99us
linear: 41us
rmsnomr_linear_2: 307us
silu_mul_linear: 170us
The reason of the slow down is the wrong formula chooses small OUTPUT_ATOM_SIZE:
BATCH_SIZE: 8, OUTPUT_SIZE: 1600, OUTPUT_ATOM_SIZE: 32, NUM_OUTPUT_ATOMS: 50, LAST_OUTPUT_ATOM_SIZE: 0
After fixing the formula, this is the statistics:
BATCH_SIZE: 8, OUTPUT_SIZE: 1600, OUTPUT_ATOM_SIZE: 128, NUM_OUTPUT_ATOMS: 12, LAST_OUTPUT_ATOM_SIZE: 64
rms_norm_1: 67us
linear: 38us
rms_norm-2: 182us
Note that silu_mul_linear is still slow and also need modifying.
Linked Issues:
- Issue # …
> [Bug] Fix MAX_OUTPUT_ATOM_SIZE calculation

- include/mirage/persistent_kernel/runtime_header.h
- python/mirage/persistent_kernel.py
The ```MAX_SHARE_MEMORY_SIZE``` attribute is used in a **host function** ```extern "C" void launch_persistent_kernel() ```, but it is defined by using the macro `__CUDA_ARCH__`, which cannot be correct defined in host function.
This pr passes a compilation flag manually to make host function correctly parse the ```MAX_SHARE_MEMORY_SIZE``` attribute.
Linked Issues:
- Issue #
- Closes #
> fix improper __CUDA_ARCH__ macro usage

- include/mirage/persistent_kernel/persistent_kernel.cuh
- include/mirage/persistent_kernel/tasks/norm_linear.cuh
- include/mirage/persistent_kernel/tasks/rotary_embedding.cuh
- include/mirage/persistent_kernel/tasks/utils.cuh
- python/mirage/utils.py
Launch 108 worker kernels instead of 96 on the A100 GPU, and launch 27 scheduler kernels simultaneously. This allows the megakernel to have more workers to perform tasks.
Linked Issues:
- Issue #
- Closes #
> Launch more workers on A100

- include/mirage/persistent_kernel/tasks/kernel.h
- include/mirage/persistent_kernel/tasks/linear_cutlass.cuh
- python/mirage/persistent_kernel.py
Add linear cutlass version implementation.
For now new end-to-end per-token latency 14.4375 ms
Batching branch before this: 16.125 ms
To let this version run correctly, we have to set __noinline__ for lineat_kernel function.
Linked Issues:
- Issue #
- Closes #
> Linear cutlass

- include/mirage/persistent_kernel/tasks/linear_cutlass.cuh
This cut down about 0.3ms (from 11.875ms to 11.5625ms) for Qwen3-8B demo with `python demo/qwen3/demo.py --use-mirage --max-num-batched-requests 1`.
1. eliminate most bank conflicts
2. update pipeline depth
Things remain to verify/fix for linear cutlass:
1. Pipeline depth of OUTPUT_SIZE 64 can be further enlarged
2. There's still a little portion of wavefronts that meet bank conflists
Linked Issues:
- Issue #
- Closes #
> Update linear cutlass kernel

- demo/qwen3/demo_hopper.py
- python/mirage/persistent_kernel.py
- src/kernel/task_register.cc
- tests/runtime_python/hopper/runtime_kernel_wrapper_hopper.cu
- tests/runtime_python/hopper/setup.py
This pr changes the `linear_layer` and `linear_layer_with_residual` partitioning strategy to always partitioning `N=64`, which means **no forloop** is required in both M/N dimension and instead we have more tasks for worker SMs to handle.
This surprisingly reduced the per token latency from ~8.25 to ~7.25ms, without changing anything in the kernels. This might indicate that we **SHOULD NOT** do too much forloop in Hopper/Blackwell kernels if we can partition the task to make several worker SMs to handle them, even if more tasks may introduce more task fetching overhead. I believe this task partitioning strategy can be more effective after we enable task descriptor prefetching in the future.
Linked Issues:
- Issue # …
> Change linear_hopper partitioning strategy

- scripts/display_task_graph.py
Added a script to visualize the task graph based off of a `task_graph.json`. Outputs a .dot file (Graphviz). One thing to note is that offsets are in terms of number of elements to align with template arguments. Example display:
> Added script to display a task_graph.json
