src/search/config.cc
src/search/dim_strategy.cc

This PR removes debugging codes introduced by mistake in #42

Remove codes for debugging

---

cpp_examples/gated_mlp.cc
cpp_examples/rms.cc
demo/demo_gated_mlp.py
include/mirage/kernel/graph.h
include/mirage/search/search_c.h
python/cython_setup.py
python/mirage/_cython/CCore.pxd
python/mirage/_cython/core.pyx
python/mirage/kernel.py
setup.py
src/kernel/graph.cc
src/search/op_utils.cc
src/search/search_c.cc

Add a new `superoptimize` function in kernel.py to search for all potential mugraphs in the configured search space. All mugraphs are profiled and the one with the best performance is returned.

[Python] update python interface to support search

---

include/mirage/search/op_utils.h
include/mirage/search/pattern_eval.h
include/mirage/search/search.h
include/mirage/search/search_context.h
src/search/op_utils.cc
src/search/pattern_eval.cc
src/search/search.cc
src/search/search_context.cc

This PR adjusts the state exploration phase of search to start parallel search earlier. Issue #75 will be fixed by this PR.

[Search] Adjust the expansion phase of search

---

include/mirage/transpiler/runtime/threadblock/element_binary.h
include/mirage/transpiler/runtime/threadblock/element_unary.h
include/mirage/transpiler/runtime/threadblock/epilogues.h
include/mirage/transpiler/runtime/threadblock/reduction.h
include/mirage/transpiler/utils.h
src/transpiler/plan_stensor_memory.cc
src/transpiler/resolve_tb_fusion.cc
src/transpiler/transpile.cc
src/transpiler/transpiler_tb.cc
tests/python/test_tensor_program.py

1. fix epilogue with scalar
2. fix stensor memory overlap issue
3. add gqa test

Fix some issues

---

include/mirage/search/irange.h
include/mirage/search/range.h
include/mirage/search/range_set.h
include/mirage/search/tbrange.h
include/mirage/utils/containers.h
src/search/config.cc
src/search/dim_strategy.cc
src/search/irange.cc
src/search/range.cc
src/search/search.cc
src/search/tbrange.cc

Constrain total number of threadblocks in search & minor update on range

---

docs/source/images/mma-non-divisible-example.drawio.svg
docs/source/images/mma-thr-layout-example.drawio.svg
docs/source/images/swizzle-shift-example.drawio.svg
docs/source/images/swizzle-xor-example.drawio.svg
docs/source/images/tb-fusion-chain.drawio.svg
docs/source/images/tb-sched-conflict-example.drawio.svg
docs/source/images/tensor-lifecycle.drawio.svg
docs/source/transpiler.rst
docs/transpiler/transpiler.md

figures and formulas at [here](https://mirage-project.readthedocs.io/en/latest/transpiler.html) are not rendered correctly
.I'm not sure how to make md file compatible with rst, maybe we should try creating a rst file for transpiler

transpiler doc fix

---

cpp_examples/chameleon.cc
cpp_examples/dnn.cc
cpp_examples/gated_mlp.cc
cpp_examples/group_query_attn_inc_decode.cc
cpp_examples/group_query_attn_prefill.cc
cpp_examples/group_query_attn_spec_decode.cc
cpp_examples/lora.cc
cpp_examples/mlp.cc
cpp_examples/moe.cc
cpp_examples/multi_head_attn_inc_decode.cc
cpp_examples/multi_head_attn_prefill.cc
cpp_examples/multi_head_attn_spec_decode.cc
cpp_examples/multi_query_attn_inc_decode.cc
cpp_examples/multi_query_attn_prefill.cc
cpp_examples/multi_query_attn_spec_decode.cc
cpp_examples/rms.cc
demo/reference_mugraphs/chameleon.py
demo/reference_mugraphs/llama3-8b.py
python/mirage/kernel.py
src/kernel/output.cc
src/transpiler/resolve_tensor_layout.cc
src/transpiler/transpile.cc
src/transpiler/transpiler_kn.cc
tests/python/test_tensor_program.py

Linked Issues:
- Issue #
- Closes #

Transpiler add input/output stride

---

python/cython_setup.py
python/mirage/__init__.py
setup.py

Update Pypi version number and CUTLASS submodule version
Linked Issues:
- Issue #
- Closes #

Update Pypi version number and CUTLASS submodule version

---

CMakeLists.txt
cpp_examples/chameleon.cc
cpp_examples/gated_mlp.cc
cpp_examples/rms.cc
demo/demo_chameleon_attn.py
demo/demo_gated_mlp.py
demo/demo_group_query_attention.py
demo/demo_lora.py
demo/demo_rms_norm.py
include/mirage/search/search.h
src/kernel/graph.cc
src/kernel/input.cc
src/kernel/output.cc
src/search/irange.cc
src/search/op_utils.cc
src/search/pattern_eval.cc
src/search/search.cc
src/threadblock/graph.cc

Linked Issues:
- Issue #
- Closes #

[Search] Support input/output strides specification

---

INSTALL.md

Update Documentation:
Added steps to build mirage as a standalone c++ library.

[Docs] Update Documentation to build C++ library

---

pyproject.toml
python/mirage/_cython/core.pyx
python/mirage/kernel.py
python/mirage/visualizer.py
requirements.txt

* Add graphviz as a prerequisite 
* Prettier prints for transpiler
Linked Issues:
- Issue #
- Closes #

[Visualizer] issue fixes

---

python/cython_setup.py
python/mirage/__init__.py
setup.py

Linked Issues:
- Issue #
- Closes #

[Version] update version number to 0.2.2

---

python/mirage/visualizer.py

Linked Issues:
- Issue #
- Closes #

[Visualizer] fix rms_norm json parse error

---

include/mirage/transpiler/runtime/threadblock/hopper_mainloop_params.h
include/mirage/transpiler/runtime/threadblock/hopper_matmul.h
include/mirage/transpiler/runtime/threadblock/input.h
include/mirage/transpiler/structs.h
include/mirage/transpiler/transpiler.h
include/mirage/transpiler/utils.h
python/cython_setup.py
setup.py
src/transpiler/plan_stensor_memory.cc
src/transpiler/plan_tb_swizzle_hopper.cc
src/transpiler/transpiler_kn.cc
src/transpiler/transpiler_tb_hopper.cc

This PR fixes the format issues of the previous H100 transpiler PR.
Linked Issues:
- Issue #
- Closes #

[Format] formatting the transpiler updates & update version to 0.2.3

---

src/transpiler/transpiler_kn.cc
src/transpiler/transpiler_tb_hopper.cc

Linked Issues:
- Issue #
- Closes #

Fix build issue caused by the previous pr

---

cpp_examples/group_query_attn_spec_decode.cc
include/mirage/threadblock/cuda/element_binary.h
include/mirage/threadblock/cuda/element_unary.h
include/mirage/threadblock/cuda/forloop_accum.h
include/mirage/threadblock/cuda/matmul.h
include/mirage/threadblock/cuda/reduction.h
include/mirage/threadblock/cuda/rms_norm.h
include/mirage/utils/cuda_helper.h
include/mirage/utils/fingerprint_functions.h
src/kernel/cuda/all_reduce_kernel.cu
src/kernel/cuda/customized_kernel.cu
src/kernel/cuda/element_binary_kernel.cu
src/kernel/cuda/element_unary_kernel.cu
src/kernel/cuda/matmul_kernel.cu
src/kernel/cuda/reduction_kernel.cu
src/kernel/cuda/rms_norm_kernel.cu

This PR adds an interface that unifies fingerprint calculation between KNOperators and TBOperators
Linked Issues:
- Issue #
- Closes #

[Fingerprint] Unify fingerprint calculation

---

include/mirage/kernel/element_unary.h
include/mirage/kernel/graph.h
include/mirage/nki_transpiler/transpile.h
include/mirage/search/abstract_expr/abstract_expr.h
include/mirage/threadblock/element_unary.h
include/mirage/transpiler/runtime/kernel/element_unary.h
include/mirage/transpiler/runtime/threadblock/element_unary.h
include/mirage/type.h
include/mirage/utils/fingerprint_functions.h
src/kernel/cuda/customized_kernel.cu
src/kernel/cuda/element_unary_kernel.cu
src/kernel/element_unary.cc
src/kernel/graph.cc
src/nki_transpiler/transpile.cc
src/nki_transpiler/transpile_tb.cc
src/search/abstract_expr/abstract_expr.cc
src/search/op_utils.cc
src/threadblock/element_unary.cc
src/triton_transpiler/transpile.cc
src/triton_transpiler/transpile_tb.cc

Implement block-level binary operator NKI kernels, this handles cases where some operators are not a part of customized operator. Plus, some format changes.
Linked Issues:
- Issue https://github.com/mirage-project/mirage/issues/185
- Closes #

Implement nki block-level binary operator kernels

---

include/mirage/transpiler/runtime/kernel/element_unary.h
include/mirage/transpiler/runtime/threadblock/element_unary.h
include/mirage/transpiler/runtime/threadblock/hopper_matmul.h
include/mirage/transpiler/runtime/threadblock/input.h
include/mirage/transpiler/runtime/threadblock/matmul.h
include/mirage/transpiler/runtime/threadblock/utils.h
include/mirage/transpiler/structs.h
include/mirage/transpiler/utils.h
src/transpiler/plan_stensor_memory.cc
src/transpiler/sched_tb_graph.cc
src/transpiler/transpiler_kn.cc
src/transpiler/transpiler_tb_hopper.cc

Linked Issues:
- Issue #
- Closes #

Hopper: Add bf16 and fix some corner cases

---

include/mirage/kernel/graph.h
python/mirage/_cython/CCore.pxd
python/mirage/_cython/core.pyx
python/mirage/kernel.py
src/kernel/graph.cc

Linked Issues:
- Issue #205 
- Closes #205

Add input dtensor shape&stride check

---

requirements.txt

Linked Issues:
- Issue #
- Closes #

[z3] enforcing z3 4.14

---

demo/reference_mugraphs/qwen_prenorm.py
src/transpiler/transpile.cc
src/transpiler/transpiler_tb.cc

Linked Issues:
- Issue #
- Closes #

Fix Qwen example alignment issue(rms normalization)

---

.github/workflows/gpu-tests.yml

Reverts mirage-project/mirage#228

Revert "Fix: Set GPU-tests to be triggered on push only"

---

demo/qwen2.5/demo.py
demo/qwen2.5/models/modeling_qwen2.py
python/cython_setup.py
python/mirage/version.py

Linked Issues:
- Issue #
- Closes #

Pre release v0.2.4

---

demo/profiler/profile_rmsnorm.py
docs/transpiler/transpiler.md
python/mirage/kernel.py

Linked Issues:
- Issue #
- Closes #

[Profiler] Add Documant

---

include/mirage/transpiler/runtime/threadblock/hopper_matmul.h
src/transpiler/transpiler_tb_hopper.cc

Linked Issues:
- Issue #
- Closes #

Remove warnings

---

cpp_examples/runtime_demo/launcher.cc
include/mirage/kernel/graph.h
src/kernel/customized.cc
src/runtime/runtime.cc

Linked Issues:
- Issue #
- Closes #

Fix some issue

---

python/mirage/kernel.py

Defer import of triton_profiler in kernel.py
Linked Issues:
- Issue #
- Closes #

defer triton

---

src/nki_transpiler/transpile_tb.cc

Add bfloat16 to support Qwen2.5
Linked Issues:
- Issue #
- Closes #

[NKI] Add bfloat16 and promote matmul accumulator to fp32

---

python/mirage/kernel.py
src/search/search.cc

- Limiting the number of threads that can be launched by the search and the transpiler. For the transpiler, this resolves the issue of it launching too many threads if a lot of mugraphs are discovered.
Linked Issues:
- Issue #
- Closes #

added thread limit

---

include/mirage/search/abstract_expr/abstract_expr.h
include/mirage/threadblock/cuda/element_unary.h
include/mirage/transpiler/runtime/threadblock/element_binary.h
include/mirage/utils/fingerprint_functions.h
src/kernel/cuda/customized_kernel.cu
src/kernel/cuda/element_unary_kernel.cu
src/kernel/triton_code_gen.cc
src/search/abstract_expr/abstract_expr.cc
src/search/config.cc
src/search/op_utils.cc
src/search/range_propagation/irange.cc
src/search/verification/formal_verifier.cc
src/triton_transpiler/transpile_tb.cc

Allow sqrt and square operators to work correctly with superoptimize.

Fix superoptimize for sqrt and square operators

---

src/transpiler/transpile.cc

Fix and simplify memory management during the graph rewriting

[Transpiler] fix bugs in graph rewriting

---

python/cython_setup.py
setup.py

add "rt" to libraries in `setup.py` and `cython_setup.py`

add "rt" to libraries

---

.github/workflows/helpers/install_dependencies.sh
conda/mirage.yml
requirements.txt
setup.py

Linked Issues:
- Issue #
- Closes #

update z3 version

---

include/mirage/persistent_kernel/persistent_kernel.cuh
include/mirage/persistent_kernel/tasks/argmax.cuh
include/mirage/persistent_kernel/tasks/kernel.h
include/mirage/persistent_kernel/tasks/linear.cuh
include/mirage/persistent_kernel/tasks/utils.cuh
tests/runtime_python/runtime_kernel_wrapper.cu
tests/runtime_python/test_argmax.py
tests/runtime_python/test_linear.py

Linked Issues:
- Issue #
- Closes #

add linear&argmax

---

include/mirage/persistent_kernel/persistent_kernel.cuh
include/mirage/persistent_kernel/tasks/linear.cuh
include/mirage/persistent_kernel/tasks/norm_linear.cuh
include/mirage/persistent_kernel/tasks/silu_mul_linear.cuh
tests/runtime_python/runtime_kernel_wrapper.cu
tests/runtime_python/test_linear.py
tests/runtime_python/test_silu_mul_linear.py

Update the implementation of tasks

update `linear` and `silu_mul_linear` tasks

---

include/mirage/persistent_kernel/persistent_kernel.cuh
include/mirage/persistent_kernel/tasks/single_batch_decoding.cuh
include/mirage/persistent_kernel/tasks/single_batch_gqa.cuh
tests/runtime_python/test_decoding_w_norm.py

Sometimes a single exp(x) can also exceed the float32 range
Linked Issues:
- Issue #
- Closes #

Fix some numeric issue

---

include/mirage/persistent_kernel/persistent_kernel.cuh
include/mirage/persistent_kernel/tasks/argmax.cuh

1. Partial argmax will get relative id
2. Parameters are moved to template to be given by compiler
Linked Issues:
- Issue #
- Closes #

Arg_max kernel modify

---

README.md

nice project, sorry, just started reading the docs and noticed a mistake, please dont be too mad for this PR
Linked Issues:
- Issue #
- Closes #

spelling fix :))))

---

INSTALL.md
demo/qwen3/demo_modal.py

Added Modal example for MPK.
Output:
Triton + FlashInfer: `Prompt length 39, generate length 264, per-token latency 30.251973470052082 ms`
MPK: `Prompt length 39, generate length 334, per-token latency 7.71875 ms`
Linked Issues:
- Issue #
- Closes #

Modal example

---

.github/ISSUE_TEMPLATE/1_Report_Bug.yml
.github/ISSUE_TEMPLATE/2_Request_Feature.yml
.github/ISSUE_TEMPLATE/3_Installation.yml
.github/ISSUE_TEMPLATE/4_Call_For_Comment.yml
.github/ISSUE_TEMPLATE/5_General.yml

Add issue template
Linked Issues:
- Issue #
- Closes #

Add issue template

---

include/mirage/persistent_kernel/tasks/kernel.h
include/mirage/persistent_kernel/tasks/paged_attention.cuh
tests/runtime_python/runtime_kernel_wrapper.cu
tests/runtime_python/test_decoding_w_norm.py
tests/runtime_python/test_paged_attention.py

**Description of change
Divide the KV Cache into pages to enable more fine-grained and efficient memory management
Linked Issues:
- Issue #358

implement paged attention

---

src/kernel/runtime.cc

Fix Triggered events and Executed tasks statistics in sanity_check()
Linked Issues:
- Issue #
- Closes #

Fix Triggered events and Executed tasks statistics

---

include/mirage/kernel/device_memory_manager.h
python/mirage/_cython/CCore.pxd
setup.py

This patch fixes the python `pip install` build issue of CPU only finger prints related work.

Fix CPU finger_prints python build

---

NCU_Usage_Manual.md
analyze.sh

Add a script and a document for using NCU to profile certain operators. This will help quickly identify bank conflict locations and make operator optimization easier.
Linked Issues:
- Issue #
- Closes #

NCU profile script & document

---

include/mirage/persistent_kernel/persistent_kernel.cuh
include/mirage/persistent_kernel/runtime_header.h
python/mirage/persistent_kernel.py

This PR makes profiling and verbose conditional compile-time macros instead of runtime flags. This would help save per-thread registers and avoids conditional branches.
Linked Issues:
- Issue #
- Closes #

Profiling macro

---

requirements.txt
setup.py

1. Fix abstract_subexpr and formal_verifier relative paths
2. Add supported version of transformers
Linked Issues:
- Issue #460 #339
- Closes #460 #339

Fix building problems
